# Generated by Django 4.2.11 on 2026-10-02 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=100, verbose_name='案件编号')),
                ('case_name', models.CharField(blank=True, max_length=200, verbose_name='案件名称')),
                ('document_no', models.CharField(max_length=100, verbose_name='法律文书编号')),
                ('authority', models.CharField(max_length=200, verbose_name='作出机关')),
                ('scope_type', models.CharField(choices=[('goods', '指定货物'), ('variety', '指定品种（冻结时在库货物）'), ('category', '指定品类（冻结时在库货物）')], max_length=20, verbose_name='范围类型')),
                ('scope_targets', models.JSONField(default=list, verbose_name='范围标识（货物/品种/品类ID）')),
                ('effective_at', models.DateTimeField(verbose_name='生效时间')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('status', models.CharField(choices=[('active', '冻结中'), ('lifted', '已解除')], default='active', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('lifted_at', models.DateTimeField(blank=True, null=True, verbose_name='解除时间')),
                ('lift_remark', models.TextField(blank=True, verbose_name='解除说明')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_freezes', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_freezes', to=settings.AUTH_USER_MODEL, verbose_name='解除人')),
            ],
            options={
                'verbose_name': '法律冻结',
                'verbose_name_plural': '法律冻结',
                'db_table': 'wh_legal_freeze',
                'ordering': ['-effective_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='转移数量')),
                ('from_location', models.CharField(blank=True, max_length=100, verbose_name='调出位置')),
                ('to_location', models.CharField(max_length=100, verbose_name='调入位置')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('transfer_time', models.DateTimeField(blank=True, null=True, verbose_name='转移时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='warehouse.goods', verbose_name='货物')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '库间转移',
                'verbose_name_plural': '库间转移',
                'db_table': 'wh_stock_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreezeBlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('stock_out', '出库'), ('transfer', '转移'), ('destruction', '销毁')], max_length=20, verbose_name='业务类型')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='业务标识')),
                ('message', models.CharField(max_length=300, verbose_name='阻断说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='阻断时间')),
                ('freeze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_logs', to='warehouse.legalfreeze', verbose_name='冻结决定')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_block_logs', to='warehouse.goods', verbose_name='货物')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freeze_blocks', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '冻结阻断记录',
                'verbose_name_plural': '冻结阻断记录',
                'db_table': 'wh_freeze_block_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestructionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='销毁数量')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='销毁事由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('completed', '已销毁')], default='pending', max_length=20, verbose_name='状态')),
                ('destroyed_at', models.DateTimeField(blank=True, null=True, verbose_name='销毁时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destruction_plans', to='warehouse.goods', verbose_name='货物')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destruction_operations', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
            options={
                'verbose_name': '销毁计划',
                'verbose_name_plural': '销毁计划',
                'db_table': 'wh_destruction_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalFreezeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name_snapshot', models.CharField(max_length=200, verbose_name='货物名称（冻结时）')),
                ('goods_code_snapshot', models.CharField(max_length=50, verbose_name='货物编码（冻结时）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入冻结时间')),
                ('freeze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.legalfreeze', verbose_name='冻结决定')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freeze_items', to='warehouse.goods', verbose_name='货物')),
            ],
            options={
                'verbose_name': '冻结范围明细',
                'verbose_name_plural': '冻结范围明细',
                'db_table': 'wh_legal_freeze_item',
                'ordering': ['goods_id'],
                'unique_together': {('freeze', 'goods')},
            },
        ),
    ]
